import type { SiteConfig } from '../types.js';

export const SITES: Record<string, SiteConfig> = {
  uk: {
    id: 'uk',
    name: 'Hercules UK',
    region: 'United Kingdom',
    language: 'English',
    locale: 'en_GB',
    url: 'https://hercules-merchandise.co.uk',
    syncWorkerUrl: 'https://hercules-product-sync-uk-production.gilles-86d.workers.dev',
    currency: { code: 'GBP', symbol: '£', htmlEntity: '&pound;', position: 'left' },
    decimalSeparator: '.',
    thousandSeparator: ',',
    cartTotalFormat: 'prefix_dot',
    taxPercent: 0,
    isHeadless: true,
    paths: {
      products: '/products',
      collections: '/collections',
      cart: '/cart',
      checkout: '/checkout',
      quoteGenerator: '/quote-generator',
      blogs: '/blogs/uk',
    },
    phone: '+442039664881',
    hasWhatsApp: false,
    emailDomain: '.co.uk',
    logoPath: '/images/hercules-logo-original1.webp',
    gtmId: 'GTM-TW5HR72',
    searchTestQuery: 'scarf',
    expectedProductCount: 97,
    benchmarkProducts: {
      attributeSimple: {
        slug: 'custom-hd-football-made-in-the-uk',
        productId: 12571,
        name: 'HD Football Scarf Made in the UK',
        type: 'attribute',
        minimumQuantity: '10',
        expectedAttributeCount: 1,
        expectedAttributes: [
          {
            slug: 'pa_format',
            displayType: 'image_selector',
            termCount: 2,
            termSlugs: ['140-x-18-cm-standard', '160-x-18-cm-extra-long'],
          },
        ],
        expectedVariationCount: 2,
        hasPrices: true,
        leadTime: '4 to 6 weeks',
        madeInEurope: false,
        greenOption: false,
        madeInUk: true,
      },
      attributeComplex: {
        slug: 'custom-football-scarf',
        productId: 6721,
        name: 'Custom HD Football Scarf',
        type: 'attribute',
        minimumQuantity: '50',
        expectedAttributeCount: 2,
        expectedAttributes: [
          {
            slug: 'pa_format',
            displayType: 'image_selector',
            termCount: 4,
            termSlugs: ['120-x-15-cm-for-kids', '140-x-18-cm-standard', '160-x-18-cm-extra-long', '180-x-18-cm-ultra-long'],
          },
          {
            slug: 'pa_colour',
            displayType: 'image_selector',
            termCount: 2,
            termSlugs: ['1-5-colours', '5-colours'],
          },
        ],
        expectedVariationCount: 8,
        hasPrices: true,
        leadTime: '4 to 6 weeks',
        madeInEurope: true,
        greenOption: false,
      },
      addonSimple: {
        slug: 'printed-t-shirt',
        productId: 10883,
        name: 'Printed t-shirt',
        type: 'addon',
        minimumQuantity: '10',
        expectedAddonCount: 4,
        expectedTopLevelAddonCount: 4,
        expectedAddons: [
          { id: 386, name: 'Textile quality', displayType: 'image_selector', parentId: 0, optionCount: 6, optionNames: ['Promotional t-shirt white (150 gsm)', 'Promotional t-shirt colour (150 gsm)', 'Premium t-shirt white (180 gsm)', 'Premium t-shirt colour (180 gsm)', 'Organic cotton t-shirt white (180 gsm)', 'Organic cotton t-shirt colour (180 gsm)'] },
          { id: 388, name: 'Front print size', displayType: 'image_selector', parentId: 0, optionCount: 4, optionNames: ['Belly (size A4)', 'Chest (Size A6)', 'Large print (size A3)', 'No print'] },
          { id: 389, name: 'Back print size', displayType: 'image_selector', parentId: 0, optionCount: 4, optionNames: ['Belly (size A4)', 'Small logo (Size A6)', 'Large print (size A3)', 'No print'] },
          { id: 390, name: 'Sleeve print size', displayType: 'image_selector', parentId: 0, optionCount: 4, optionNames: ['Both sleeves', 'Right sleeve', 'Left sleeve', 'No prints'] },
        ],
        expectedVariationCount: 1,
        hasPrices: false,
        leadTime: 'About 3 weeks',
        madeInEurope: false,
        greenOption: true,
      },
      addonComplex: {
        slug: 'baseball-cap',
        productId: 10105,
        name: 'Baseball cap',
        type: 'addon',
        minimumQuantity: '10',
        expectedAddonCount: 12,
        expectedTopLevelAddonCount: 4,
        expectedAddons: [
          { id: 72, name: 'Cap front decoration', displayType: 'image_selector', parentId: 0, optionCount: 5, optionNames: ['Embroidery', 'Print', 'Woven patch', 'Sublimation patch', 'Leather badge'] },
          { id: 75, name: 'Cap back decoration', displayType: 'image_selector', parentId: 0, optionCount: 4, optionNames: ['None', 'Embroidery', 'Print', 'Leather badge'] },
          { id: 79, name: 'Cap side decoration', displayType: 'image_selector', parentId: 0, optionCount: 6, optionNames: ['None', 'Embroidery', 'Print', 'Woven patch', 'Sublimation patch', 'Leather badge'] },
          { id: 80, name: 'Accessory', displayType: 'multiple_choise', parentId: 0, optionCount: 3, optionNames: ['None', 'Care label', 'Woven flag label'] },
        ],
        expectedVariationCount: 1,
        hasPrices: true,
        leadTime: 'About 4 weeks',
        madeInEurope: false,
        greenOption: false,
      },
    },
    benchmarkCategories: [
      { slug: 'custom-scarves', name: 'Custom Scarves', expectedProductCount: 16, tolerance: 5 },
      { slug: 'football', name: 'Football', expectedProductCount: 28, tolerance: 5 },
      { slug: 'custom-printed-sportswear', name: 'Custom Sportswear', expectedProductCount: 20, tolerance: 5 },
    ],
  },

  de: {
    id: 'de',
    name: 'Hercules DE',
    region: 'Germany',
    language: 'German',
    locale: 'de_DE',
    url: 'https://hercules-merchandise.de',
    syncWorkerUrl: 'https://hercules-product-sync-live-production.gilles-86d.workers.dev',
    currency: { code: 'EUR', symbol: '€', htmlEntity: '&euro;', position: 'left_space' },
    decimalSeparator: ',',
    thousandSeparator: '.',
    cartTotalFormat: 'prefix_dot_de',
    taxPercent: 19,
    isHeadless: true,
    paths: {
      products: '/produkte',
      collections: '/kollektionen',
      cart: '/warenkorb',
      checkout: '/kasse',
      quoteGenerator: '/quote-generator',
      blogs: '/blogs/de',
    },
    phone: '+49 8001833745',
    hasWhatsApp: false,
    emailDomain: '.de',
    logoPath: '/images/logo.png',
    gtmId: 'GTM-MJKQ32P5',
    searchTestQuery: 'schal',
    expectedProductCount: 40,
    benchmarkProducts: {
      attributeSimple: {
        slug: 'personalisiertes-laufshirt-2',
        productId: 4184,
        name: 'Personalisiertes Laufshirt',
        type: 'attribute',
        minimumQuantity: '5',
        expectedAttributeCount: 1,
        expectedAttributes: [
          { slug: 'pa_qualitat', displayType: 'select_boxes', termCount: 3, termSlugs: ['nachhaltig', 'premium', 'standard-2'] },
        ],
        expectedVariationCount: 0,
        hasPrices: true,
        leadTime: '4 bis 6 Wochen',
        madeInEurope: true,
        greenOption: false,
      },
      attributeComplex: {
        slug: 'personalisierter-fussballschal',
        productId: 6721,
        name: 'Personalisierter HD-Fußballschal',
        type: 'attribute',
        minimumQuantity: '50',
        expectedAttributeCount: 2,
        expectedAttributes: [
          { slug: 'pa_format', displayType: 'image_selector', termCount: 4, termSlugs: ['120-x-15-cm-fur-kinder', '140-x-18-cm-standard', '160-x-18-cm-extra-lang', '180-x-18-cm-ultra-lang'] },
          { slug: 'pa_farbe', displayType: 'image_selector', termCount: 2, termSlugs: ['1-5-farben', '5-farben'] },
        ],
        expectedVariationCount: 8,
        hasPrices: true,
        leadTime: '4 bis 6 Wochen',
        madeInEurope: true,
        greenOption: false,
      },
      addonSimple: {
        slug: 'bedrucktes-tshirt',
        productId: 10883,
        name: 'Bedrucktes T-Shirt',
        type: 'addon',
        minimumQuantity: '10',
        expectedAddonCount: 4,
        expectedTopLevelAddonCount: 4,
        expectedAddons: [
          { id: 386, name: 'Textilqualität', displayType: 'image_selector', parentId: 0, optionCount: 6, optionNames: [] },
          { id: 388, name: 'Vorderseitige Druckgröße', displayType: 'image_selector', parentId: 0, optionCount: 4, optionNames: [] },
          { id: 389, name: 'Rückseitige Druckgröße', displayType: 'image_selector', parentId: 0, optionCount: 4, optionNames: [] },
          { id: 390, name: 'Druckgröße auf den Ärmeln', displayType: 'image_selector', parentId: 0, optionCount: 4, optionNames: [] },
        ],
        expectedVariationCount: 1,
        hasPrices: false,
        leadTime: 'Etwa 3 Wochen',
        madeInEurope: false,
        greenOption: true,
      },
      addonComplex: {
        slug: 'baseball-cap',
        productId: 10105,
        name: 'Basecap',
        type: 'addon',
        minimumQuantity: '10',
        expectedAddonCount: 12,
        expectedTopLevelAddonCount: 4,
        expectedAddons: [
          { id: 72, name: 'Vorderseitige Gestaltung der Cap', displayType: 'image_selector', parentId: 0, optionCount: 5, optionNames: [] },
          { id: 75, name: 'Rückseitengestaltung der Cap', displayType: 'image_selector', parentId: 0, optionCount: 4, optionNames: [] },
          { id: 79, name: 'Seitengestaltung der Cap', displayType: 'image_selector', parentId: 0, optionCount: 6, optionNames: [] },
          { id: 80, name: 'Zubehör', displayType: 'multiple_choise', parentId: 0, optionCount: 3, optionNames: [] },
        ],
        expectedVariationCount: 1,
        hasPrices: true,
        leadTime: 'Etwa 4 Wochen',
        madeInEurope: false,
        greenOption: false,
      },
    },
    benchmarkCategories: [
      { slug: 'fussballschals', name: 'Fußballschals', expectedProductCount: 18, tolerance: 5 },
      { slug: 'fussball', name: 'Fußball', expectedProductCount: 27, tolerance: 5 },
      { slug: 'personalisierte-sportbekleidung', name: 'Personalisierte Sportbekleidung', expectedProductCount: 20, tolerance: 5 },
    ],
  },

  fr: {
    id: 'fr',
    name: 'Hercules FR',
    region: 'France',
    language: 'French',
    locale: 'fr_FR',
    url: 'https://hercules-merchandising.fr',
    syncWorkerUrl: 'https://hercules-product-sync-fr-prod.gilles-86d.workers.dev',
    currency: { code: 'EUR', symbol: '€', htmlEntity: '&euro;', position: 'right_space' },
    decimalSeparator: ',',
    thousandSeparator: ' ',
    cartTotalFormat: 'suffix_comma',
    taxPercent: 20,
    isHeadless: true,
    paths: {
      products: '/products',
      collections: '/collections',
      cart: '/panier',
      checkout: '/paiement',
      quoteGenerator: '/generateur-de-devis',
      blogs: '/blog',
    },
    phone: '+33973030295',
    hasWhatsApp: false,
    emailDomain: '.fr',
    logoPath: '/images/logo.png',
    gtmId: 'GTM-N7NM77N',
    searchTestQuery: 'echarpe',
    expectedProductCount: 97,
    benchmarkProducts: {
      attributeSimple: {
        slug: 'maillot-running-personnalise',
        productId: 0,
        name: 'Maillot Running Personnalisé',
        type: 'attribute',
        minimumQuantity: '5',
        expectedAttributeCount: 2,
        expectedAttributes: [
          { slug: 'pa_origine-maillot-running', displayType: 'image_selector', termCount: 2, termSlugs: ['production-en-chine', 'production-en-europe'] },
          { slug: 'pa_qualite-maillot-running', displayType: 'image_selector', termCount: 5, termSlugs: ['matiere-lisse', 'matiere-perforee', 'qualite-pro', 'qualite-promotionnelle', 'qualite-recyclee'] },
        ],
        expectedVariationCount: 5,
        hasPrices: true,
        leadTime: '4 à 6 semaines',
        madeInEurope: true,
        greenOption: false,
      },
      attributeComplex: {
        slug: 'echarpe-hd-deluxe-personnalisee',
        productId: 6721,
        name: 'Écharpe personnalisée HD Deluxe',
        type: 'attribute',
        minimumQuantity: '50',
        expectedAttributeCount: 2,
        expectedAttributes: [
          { slug: 'pa_format', displayType: 'image_selector', termCount: 4, termSlugs: ['120-x-15-cm-pour-les-enfants', '140-x-18-cm-standard', '160-x-18-cm-extra-long', '180-x-18-cm-ultra-long'] },
          { slug: 'pa_couleur', displayType: 'image_selector', termCount: 2, termSlugs: ['1-a-5-couleurs', '5-couleurs'] },
        ],
        expectedVariationCount: 8,
        hasPrices: true,
        leadTime: '4 à 6 semaines',
        madeInEurope: true,
        greenOption: false,
      },
      addonSimple: {
        slug: 't-shirt-personnalise',
        productId: 10883,
        name: 'T-shirt Personnalisé',
        type: 'addon',
        minimumQuantity: '10',
        expectedAddonCount: 4,
        expectedTopLevelAddonCount: 4,
        expectedAddons: [
          { id: 386, name: 'Qualité du textile', displayType: 'image_selector', parentId: 0, optionCount: 6, optionNames: [] },
          { id: 388, name: "Taille d'impression avant", displayType: 'image_selector', parentId: 0, optionCount: 4, optionNames: [] },
          { id: 389, name: "Taille d'impression dos", displayType: 'image_selector', parentId: 0, optionCount: 4, optionNames: [] },
          { id: 390, name: "Taille d'impression manche", displayType: 'image_selector', parentId: 0, optionCount: 4, optionNames: [] },
        ],
        expectedVariationCount: 1,
        hasPrices: false,
        leadTime: 'Environ 3 semaines',
        madeInEurope: false,
        greenOption: true,
      },
      addonComplex: {
        slug: 'casquette-de-baseball',
        productId: 10105,
        name: 'Casquette de baseball',
        type: 'addon',
        minimumQuantity: '10',
        expectedAddonCount: 12,
        expectedTopLevelAddonCount: 4,
        expectedAddons: [
          { id: 72, name: 'Décoration avant de la casquette', displayType: 'image_selector', parentId: 0, optionCount: 5, optionNames: [] },
          { id: 75, name: 'Décoration arrière de la casquette', displayType: 'image_selector', parentId: 0, optionCount: 4, optionNames: [] },
          { id: 79, name: 'Décoration latérale de la casquette', displayType: 'image_selector', parentId: 0, optionCount: 6, optionNames: [] },
          { id: 80, name: 'Accessoire', displayType: 'multiple_choise', parentId: 0, optionCount: 3, optionNames: [] },
        ],
        expectedVariationCount: 1,
        hasPrices: true,
        leadTime: 'Environ 4 semaines',
        madeInEurope: false,
        greenOption: false,
      },
    },
    benchmarkCategories: [
      { slug: 'echarpes-de-football', name: 'Écharpes de Football', expectedProductCount: 17, tolerance: 5 },
      { slug: 'football', name: 'Football', expectedProductCount: 27, tolerance: 5 },
      { slug: 'equipements-personnalises', name: 'Equipements Personnalisés', expectedProductCount: 20, tolerance: 5 },
    ],
  },
};

export const ALERT_EMAILS = process.env.ALERT_EMAIL_OVERRIDE
  ? [process.env.ALERT_EMAIL_OVERRIDE]
  : ['roy@perelweb.studio', 'kamindudushmantha@gmail.com', 'gilles@hercules-merchandise.com'];
export const DEPLOY_EMAILS = ['kamindudushmantha@gmail.com'];

export const BREVO_API_KEY = process.env.BREVO_API_KEY || '';

export const TIMEOUTS = {
  page: 15000,
  api: 10000,
  image: 8000,
};
